package com.example.focususerapp

import android.content.Context

object AppText {
    private val ro = mapOf(
        "FOCUS" to "FOCUS",
        "Back" to "Inapoi",
        "Sign out" to "Deconectare",
        "My Account" to "Contul meu",
        "Test Results" to "Rezultate teste",
        "Games" to "Jocuri",
        "Settings" to "Setari",
        "Welcome back" to "Bine ai revenit",
        "Sign in to continue" to "Autentifica-te pentru a continua",
        "EMAIL" to "EMAIL",
        "PASSWORD" to "PAROLA",
        "Forgot password?" to "Ai uitat parola?",
        "SIGN IN" to "AUTENTIFICARE",
        "or" to "sau",
        "Continue with Google" to "Continua cu Google",
        "Connecting..." to "Se conecteaza...",
        "SIGNING IN..." to "SE AUTENTIFICA...",
        "Enter email first" to "Introdu emailul mai intai",
        "Reset email sent!" to "Email de resetare trimis!",
        "Invalid email" to "Email invalid",
        "Minimum 6 characters" to "Minimum 6 caractere",
        "Don't have an account? " to "Nu ai cont? ",
        "Sign up" to "Creeaza cont",
        "Create account" to "Creeaza cont",
        "CREATE ACCOUNT" to "CREEAZA CONT",
        "CREATING..." to "SE CREEAZA...",
        "Already have an account? " to "Ai deja cont? ",
        "Log in" to "Autentifica-te",
        "Required" to "Obligatoriu",
        "Min 6 chars" to "Minim 6 caractere",
        "Passwords don't match" to "Parolele nu coincid",
        "SAVE & CONTINUE" to "SALVEAZA SI CONTINUA",
        "SAVING..." to "SE SALVEAZA...",
        "Hello" to "Salut",
        "Choose a game" to "Alege un joc",
        "Play quick cognitive exercises and save every result in Firebase." to "Joaca exercitii cognitive rapide si salveaza fiecare rezultat in Firebase.",
        "Quick Math" to "Calcul Rapid",
        "Solve operations in 60 seconds." to "Rezolva operatii in 60 de secunde.",
        "Memory" to "Memorie",
        "Find all matching card pairs." to "Gaseste toate perechile de carti.",
        "Sequences" to "Secvente",
        "Watch and repeat the growing sequence." to "Urmareste si repeta secventa.",
        "Stroop Test" to "Test Stroop",
        "Pick the text color, not the word." to "Alege culoarea textului, nu cuvantul.",
        "Visual Search" to "Cautare Vizuala",
        "Find the odd character before time runs out." to "Gaseste caracterul diferit inainte sa expire timpul.",
        "History" to "Istoric",
        "No games played yet" to "Nu exista jocuri jucate inca",
        "Choose difficulty" to "Alege dificultatea",
        "Easy" to "Usor",
        "Medium" to "Mediu",
        "Hard" to "Greu",
        "Play" to "Joaca",
        "Appearance" to "Aspect",
        "Language" to "Limba",
        "Dark mode" to "Mod intunecat",
        "Light mode" to "Mod luminos",
        "English" to "Engleza",
        "Romanian" to "Romana",
        "Turkish" to "Turca",
        "App settings" to "Setari aplicatie",
        "Choose the theme and language used by the app." to "Alege tema si limba folosita de aplicatie.",
        "Theme updated" to "Tema actualizata",
        "Language updated" to "Limba actualizata",
        "No chart data" to "Nu exista date pentru grafic",
        "No map data" to "Nu exista date pentru harta",
        "Join FOCUS today" to "Alatura-te FOCUS astazi",
        "FULL NAME" to "NUME COMPLET",
        "CONFIRM PASSWORD" to "CONFIRMA PAROLA",
        "Sign in" to "Autentifica-te",
        "min. 6 caractere" to "min. 6 caractere",
        "repeat password" to "repeta parola",
        "Complete your profile to continue" to "Completeaza profilul pentru a continua",
        "BIRTH DATE" to "DATA NASTERII",
        "PHONE NUMBER" to "NUMAR DE TELEFON",
        "DOCTOR INFO  (optional)" to "DATE MEDIC  (optional)",
        "DOCTOR EMAIL" to "EMAIL MEDIC",
        "DOCTOR PHONE" to "TELEFON MEDIC",
        "Loading" to "Se incarca",
        "Unnamed patient" to "Pacient fara nume",
        "No email" to "Fara email",
        "Name" to "Nume",
        "Surname" to "Prenume",
        "Email" to "Email",
        "Phone" to "Telefon",
        "Birth date" to "Data nasterii",
        "Not set" to "Nesetat",
        "No test results available" to "Nu exista rezultate disponibile",
        "View details" to "Vezi detalii",
        "Hide details" to "Ascunde detalii",
        "Duration" to "Durata",
        "Average distance" to "Distanta medie",
        "Go/No-Go accuracy" to "Acuratete Go/No-Go",
        "Map" to "Harta",
        "Test" to "Test",
        "No date" to "Fara data",
        "Error loading account data" to "Eroare la incarcarea datelor contului",
        "Answer" to "Raspuns",
        "Solve as many operations as possible." to "Rezolva cat mai multe operatii.",
        "Submit" to "Trimite",
        "Correct" to "Corect",
        "Wrong" to "Gresit",
        "Wrong. Answer:" to "Gresit. Raspuns:",
        "Score" to "Scor",
        "Moves" to "Mutari",
        "Pairs" to "Perechi",
        "Find every pair." to "Gaseste fiecare pereche.",
        "Level" to "Nivel",
        "Lives" to "Vieti",
        "Watch the sequence" to "Urmareste secventa",
        "Repeat it" to "Repeta secventa",
        "Wrong. Watch again" to "Gresit. Urmareste din nou",
        "Memorize and repeat." to "Memoreaza si repeta.",
        "Round" to "Runda",
        "RED" to "ROSU",
        "GREEN" to "VERDE",
        "BLUE" to "ALBASTRU",
        "YELLOW" to "GALBEN",
        "ORANGE" to "PORTOCALIU",
        "PURPLE" to "MOV",
        "Choose the ink color." to "Alege culoarea cernelii.",
        "Find the odd character." to "Gaseste caracterul diferit.",
        "Result saved" to "Rezultat salvat",
        "Could not save result" to "Nu s-a putut salva rezultatul",
        "Could not load game history" to "Nu s-a putut incarca istoricul jocurilor",
        "Result" to "Rezultat",
        "Back to Games" to "Inapoi la jocuri",
        "Game" to "Joc",
        "correct" to "corecte",
        "wrong" to "gresite",
        "Best streak" to "Cea mai buna serie",
        "Time" to "Timp",
        "Level reached" to "Nivel atins"
        ,"NFC tag" to "Tag NFC"
        ,"Setup NFC" to "Configureaza NFC"
        ,"Replace NFC" to "Schimba NFC"
        ,"Ready to scan NFC" to "Apropie tagul NFC de telefon"
        ,"NFC saved" to "NFC salvat"
        ,"Could not save NFC" to "Nu s-a putut salva NFC-ul"
        ,"NFC is not available on this phone" to "NFC nu este disponibil pe acest telefon"
        ,"Please enable NFC and try again" to "Activeaza NFC si incearca din nou"
        ,"Change NFC tag?" to "Schimbi tagul NFC?"
        ,"This patient already has an NFC tag. Do you want to replace it?" to "Pacientul are deja un tag NFC. Vrei sa il inlocuiesti?"
        ,"Yes, replace" to "Da, inlocuieste"
        ,"Cancel" to "Anuleaza"
    )

    private val tr = mapOf(
        "FOCUS" to "FOCUS",
        "Back" to "Geri",
        "Sign out" to "Cikis yap",
        "My Account" to "Hesabim",
        "Test Results" to "Test Sonuclari",
        "Games" to "Oyunlar",
        "Settings" to "Ayarlar",
        "Welcome back" to "Hos geldiniz",
        "Sign in to continue" to "Devam etmek icin giris yapin",
        "EMAIL" to "E-POSTA",
        "PASSWORD" to "SIFRE",
        "Forgot password?" to "Sifrenizi mi unuttunuz?",
        "SIGN IN" to "GIRIS YAP",
        "or" to "veya",
        "Continue with Google" to "Google ile devam et",
        "Connecting..." to "Baglaniyor...",
        "SIGNING IN..." to "GIRIS YAPILIYOR...",
        "Enter email first" to "Once e-postanizi girin",
        "Reset email sent!" to "Sifirlama e-postasi gonderildi!",
        "Invalid email" to "Gecersiz e-posta",
        "Minimum 6 characters" to "En az 6 karakter",
        "Don't have an account? " to "Hesabiniz yok mu? ",
        "Sign up" to "Kaydol",
        "Create account" to "Hesap olustur",
        "CREATE ACCOUNT" to "HESAP OLUSTUR",
        "CREATING..." to "OLUSTURULUYOR...",
        "Already have an account? " to "Zaten hesabiniz var mi? ",
        "Log in" to "Giris yap",
        "Required" to "Gerekli",
        "Min 6 chars" to "En az 6 karakter",
        "Passwords don't match" to "Sifreler eslesmiyor",
        "SAVE & CONTINUE" to "KAYDET VE DEVAM ET",
        "SAVING..." to "KAYDEDILIYOR...",
        "Hello" to "Merhaba",
        "Choose a game" to "Bir oyun secin",
        "Play quick cognitive exercises and save every result in Firebase." to "Hizli bilissel egzersizler oynayin ve her sonucu Firebase'e kaydedin.",
        "Quick Math" to "Hizli Matematik",
        "Solve operations in 60 seconds." to "60 saniyede islemleri cozun.",
        "Memory" to "Hafiza",
        "Find all matching card pairs." to "Tum eslesen kart ciftlerini bulun.",
        "Sequences" to "Diziler",
        "Watch and repeat the growing sequence." to "Buyuyen diziyi izleyin ve tekrarlayin.",
        "Stroop Test" to "Stroop Testi",
        "Pick the text color, not the word." to "Kelimeyi degil, metin rengini secin.",
        "Visual Search" to "Gorsel Arama",
        "Find the odd character before time runs out." to "Sure dolmadan farkli karakteri bulun.",
        "History" to "Gecmis",
        "No games played yet" to "Henuz oyun oynanmadi",
        "Choose difficulty" to "Zorluk secin",
        "Easy" to "Kolay",
        "Medium" to "Orta",
        "Hard" to "Zor",
        "Play" to "Oyna",
        "Appearance" to "Gorunum",
        "Language" to "Dil",
        "Dark mode" to "Karanlik mod",
        "Light mode" to "Aydinlik mod",
        "English" to "Ingilizce",
        "Romanian" to "Rumence",
        "Turkish" to "Turkce",
        "App settings" to "Uygulama ayarlari",
        "Choose the theme and language used by the app." to "Uygulamanin temasini ve dilini secin.",
        "Theme updated" to "Tema guncellendi",
        "Language updated" to "Dil guncellendi",
        "No chart data" to "Grafik verisi yok",
        "No map data" to "Harita verisi yok",
        "Join FOCUS today" to "Bugun FOCUS'a katilin",
        "FULL NAME" to "AD SOYAD",
        "CONFIRM PASSWORD" to "SIFREYI ONAYLA",
        "Sign in" to "Giris yap",
        "min. 6 caractere" to "min. 6 karakter",
        "repeat password" to "sifreyi tekrarla",
        "Complete your profile to continue" to "Devam etmek icin profilinizi tamamlayin",
        "BIRTH DATE" to "DOGUM TARIHI",
        "PHONE NUMBER" to "TELEFON NUMARASI",
        "DOCTOR INFO  (optional)" to "DOKTOR BILGISI  (istege bagli)",
        "DOCTOR EMAIL" to "DOKTOR E-POSTA",
        "DOCTOR PHONE" to "DOKTOR TELEFON",
        "Loading" to "Yukleniyor",
        "Unnamed patient" to "Adsiz hasta",
        "No email" to "E-posta yok",
        "Name" to "Ad",
        "Surname" to "Soyad",
        "Email" to "E-posta",
        "Phone" to "Telefon",
        "Birth date" to "Dogum tarihi",
        "Not set" to "Ayarlanmadi",
        "No test results available" to "Test sonucu yok",
        "View details" to "Detaylari gor",
        "Hide details" to "Detaylari gizle",
        "Duration" to "Sure",
        "Average distance" to "Ortalama mesafe",
        "Go/No-Go accuracy" to "Go/No-Go dogrulugu",
        "Map" to "Harita",
        "Test" to "Test",
        "No date" to "Tarih yok",
        "Error loading account data" to "Hesap verileri yuklenemedi",
        "Answer" to "Cevap",
        "Solve as many operations as possible." to "Mumkun oldugunca cok islem cozun.",
        "Submit" to "Gonder",
        "Correct" to "Dogru",
        "Wrong" to "Yanlis",
        "Wrong. Answer:" to "Yanlis. Cevap:",
        "Score" to "Puan",
        "Moves" to "Hamleler",
        "Pairs" to "Ciftler",
        "Find every pair." to "Her cifti bulun.",
        "Level" to "Seviye",
        "Lives" to "Can",
        "Watch the sequence" to "Diziyi izle",
        "Repeat it" to "Tekrarla",
        "Wrong. Watch again" to "Yanlis. Tekrar izle",
        "Memorize and repeat." to "Ezberle ve tekrarla.",
        "Round" to "Tur",
        "RED" to "KIRMIZI",
        "GREEN" to "YESIL",
        "BLUE" to "MAVI",
        "YELLOW" to "SARI",
        "ORANGE" to "TURUNCU",
        "PURPLE" to "MOR",
        "Choose the ink color." to "Yazi rengini secin.",
        "Find the odd character." to "Farkli karakteri bulun.",
        "Result saved" to "Sonuc kaydedildi",
        "Could not save result" to "Sonuc kaydedilemedi",
        "Could not load game history" to "Oyun gecmisi yuklenemedi",
        "Result" to "Sonuc",
        "Back to Games" to "Oyunlara don",
        "Game" to "Oyun",
        "correct" to "dogru",
        "wrong" to "yanlis",
        "Best streak" to "En iyi seri",
        "Time" to "Sure",
        "Level reached" to "Ulasilan seviye"
        ,"NFC tag" to "NFC etiketi"
        ,"Setup NFC" to "NFC ayarla"
        ,"Replace NFC" to "NFC degistir"
        ,"Ready to scan NFC" to "NFC etiketini telefona yaklastirin"
        ,"NFC saved" to "NFC kaydedildi"
        ,"Could not save NFC" to "NFC kaydedilemedi"
        ,"NFC is not available on this phone" to "Bu telefonda NFC yok"
        ,"Please enable NFC and try again" to "NFC'yi acip tekrar deneyin"
        ,"Change NFC tag?" to "NFC etiketi degissin mi?"
        ,"This patient already has an NFC tag. Do you want to replace it?" to "Bu hastanin zaten NFC etiketi var. Degistirmek istiyor musunuz?"
        ,"Yes, replace" to "Evet, degistir"
        ,"Cancel" to "Iptal"
    )

    private val canonical = buildMap {
        ro.forEach { (key, value) -> put(value, key) }
        tr.forEach { (key, value) -> put(value, key) }
    }

    fun keyFor(text: String): String = canonical[text] ?: text

    fun get(context: Context, text: String): String {
        val key = keyFor(text)
        return when (AppSettings.language(context)) {
            AppSettings.LANG_RO -> ro[key] ?: key
            AppSettings.LANG_TR -> tr[key] ?: key
            else -> key
        }
    }
}
